server:
  port: 9776

spring:
  profiles:
    active: prod1
  redis:
    key-prefix: prod  # redis key的前缀， 环境的多个实例一定要配置一样（即prod1和prod2文件中需要配置一致）
    host: 47.106.89.28
  rabbitmq:
    host: 47.106.89.28
    port: 5672
    username: root
    password: 123456

zuihou:
  mysql:
    admin:
      database: zuihou_admin_prod

logging:
  level:
    console: WARN
    filter: WARN


id-generator:
  machine-code: 1  # id生成器机器掩码


# rabbitMQ/Mysql/Redis ip，端口，帐号等根据环境自行修改。